package dao;

// Generated 4 mars 2015 09:46:52 by Hibernate Tools 3.4.0.CR1

/**
 * Admin generated by hbm2java
 */
public class Admin implements java.io.Serializable 
{

	private Integer idadmin;
	private String emailuser;
	private String login;
	private String nomuser;
	private String password;
	private String phoneuser;
	private String prenomuser;

	public Admin() {
	}

	public Admin(String emailuser, String login, String nomuser,
			String password, String phoneuser, String prenomuser) {
		this.emailuser = emailuser;
		this.login = login;
		this.nomuser = nomuser;
		this.password = password;
		this.phoneuser = phoneuser;
		this.prenomuser = prenomuser;
	}
	
	
	public Integer getIdadmin() {
		return this.idadmin;
	}

	public void setIdadmin(Integer idadmin) {
		this.idadmin = idadmin;
	}

	public String getEmailuser() {
		return this.emailuser;
	}

	public void setEmailuser(String emailuser) {
		this.emailuser = emailuser;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getNomuser() {
		return this.nomuser;
	}

	public void setNomuser(String nomuser) {
		this.nomuser = nomuser;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getPhoneuser() {
		return this.phoneuser;
	}

	public void setPhoneuser(String phoneuser) {
		this.phoneuser = phoneuser;
	}

	public String getPrenomuser() {
		return this.prenomuser;
	}

	public void setPrenomuser(String prenomuser) {
		this.prenomuser = prenomuser;
	}

}
