package dao;

// Generated 4 mars 2015 09:46:52 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Client generated by hbm2java
 */
public class Client implements java.io.Serializable {

	private Integer idclient;
	private String adresseclient;
	private String emailclient;
	private String nomclient;
	private String phoneclient;
	private String prenomclient;
	private String login;
	private String pssword;
	private Set<Dossier> dossiers = new HashSet<Dossier>(0);

	public Client() {
	}

	public Client(String adresseclient, String emailclient, String nomclient,
			String phoneclient, String prenomclient, String login,
			String pssword) {
		this.adresseclient = adresseclient;
		this.emailclient = emailclient;
		this.nomclient = nomclient;
		this.phoneclient = phoneclient;
		this.prenomclient = prenomclient;
		this.login = login;
		this.pssword = pssword;
	}

	public Client(String adresseclient, String emailclient, String nomclient,
			String phoneclient, String prenomclient, String login,
			String pssword, Set<Dossier> dossiers) {
		this.adresseclient = adresseclient;
		this.emailclient = emailclient;
		this.nomclient = nomclient;
		this.phoneclient = phoneclient;
		this.prenomclient = prenomclient;
		this.login = login;
		this.pssword = pssword;
		this.dossiers = dossiers;
	}

	public Integer getIdclient() {
		return this.idclient;
	}

	public void setIdclient(Integer idclient) {
		this.idclient = idclient;
	}

	public String getAdresseclient() {
		return this.adresseclient;
	}

	public void setAdresseclient(String adresseclient) {
		this.adresseclient = adresseclient;
	}

	public String getEmailclient() {
		return this.emailclient;
	}

	public void setEmailclient(String emailclient) {
		this.emailclient = emailclient;
	}

	public String getNomclient() {
		return this.nomclient;
	}

	public void setNomclient(String nomclient) {
		this.nomclient = nomclient;
	}

	public String getPhoneclient() {
		return this.phoneclient;
	}

	public void setPhoneclient(String phoneclient) {
		this.phoneclient = phoneclient;
	}

	public String getPrenomclient() {
		return this.prenomclient;
	}

	public void setPrenomclient(String prenomclient) {
		this.prenomclient = prenomclient;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getPssword() {
		return this.pssword;
	}

	public void setPssword(String pssword) {
		this.pssword = pssword;
	}

	public Set<Dossier> getDossiers() {
		return this.dossiers;
	}

	public void setDossiers(Set<Dossier> dossiers) {
		this.dossiers = dossiers;
	}

}
