package dao;

// Generated 4 mars 2015 09:46:52 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Dossier generated by hbm2java
 */
public class Dossier implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer numdossier;
	private int delaiTransit;
	private Client client;
	private Transporteur transporteur;
	private Port portByIdport;
	private Port portByPorIdport;
	private Moyennetransport moyennetransport;
	private Transit transit;
	private Commercial commercial;
	private Double cotation;
	private Date date;
	private String etat;
	private String incoter;
	private String typetransport;
	private Boolean fintransport;
	private Boolean validationclient;
	private Set<Comment> commentaires = new HashSet<Comment>(0);
	private Set<Etat> etats = new HashSet<Etat>(0);

	public Dossier() {
	}
	

	public Dossier(int delaiTransit, Client client,
			Port portByIdport, Port portByPorIdport,
			Moyennetransport moyennetransport, Double cotation, Date date,
			String etat, String incoter, String typetransport,Commercial commercial,
			Boolean validationclient,Boolean fintransport) {
		this.delaiTransit = delaiTransit;
		this.client = client;
		this.portByIdport = portByIdport;
		this.portByPorIdport = portByPorIdport;
		this.moyennetransport = moyennetransport;
		this.cotation = cotation;
		this.date = date;
		this.etat = etat;
		this.incoter = incoter;
		this.commercial = commercial;
		this.typetransport = typetransport;
		this.validationclient = validationclient;
		this.fintransport = fintransport;
	}
	
	public Dossier(int delaiTransit, Client client,
			Port portByIdport, Port portByPorIdport,
			Moyennetransport moyennetransport, Double cotation, Date date,
			String etat, String incoter, String typetransport,Transit transit,
			Boolean validationclient,Boolean fintransport) {
		this.delaiTransit = delaiTransit;
		this.client = client;
		this.portByIdport = portByIdport;
		this.portByPorIdport = portByPorIdport;
		this.moyennetransport = moyennetransport;
		this.cotation = cotation;
		this.date = date;
		this.etat = etat;
		this.incoter = incoter;
		this.transit = transit;
		this.typetransport = typetransport;
		this.validationclient = validationclient;
		this.fintransport = fintransport;
	}
	
	public Dossier(int delaiTransit, Client client,
			Port portByIdport, Port portByPorIdport,
			Moyennetransport moyennetransport, Double cotation, Date date,
			String etat, String incoter, String typetransport,Transporteur transporteur,
			Boolean validationclient,Boolean fintransport) {
		this.delaiTransit = delaiTransit;
		this.client = client;
		this.portByIdport = portByIdport;
		this.portByPorIdport = portByPorIdport;
		this.moyennetransport = moyennetransport;
		this.cotation = cotation;
		this.date = date;
		this.etat = etat;
		this.incoter = incoter;
		this.transporteur = transporteur;
		this.typetransport = typetransport;
		this.validationclient = validationclient;
		this.fintransport = fintransport;
	}
	
	public Dossier(Client client, Transporteur transporteur, Port portByIdport,
			Port portByPorIdport, Moyennetransport moyennetransport,
			Transit transit, Commercial commercial, Double cotation, Date date,
			String etat, String incoter, String typetransport,
			Boolean fintransport, Boolean validationclient) {
		
		System.out.println("Const 1");
		
		this.client = client;
		this.transporteur = transporteur;
		this.portByIdport = portByIdport;
		this.portByPorIdport = portByPorIdport;
		this.moyennetransport = moyennetransport;
		this.transit = transit;
		this.commercial = commercial;
		this.cotation = cotation;
		this.date = date;
		this.etat = etat;
		this.incoter = incoter;
		this.typetransport = typetransport;
		this.fintransport = fintransport;
		this.validationclient = validationclient;
	}

	public Dossier(int delaiTransit, Client client,
			Transporteur transporteur, Port portByIdport, Port portByPorIdport,
			Moyennetransport moyennetransport, Transit transit,
			Commercial commercial, Double cotation, Date date, String etat,
			String incoter, String typetransport) {
		
		this.delaiTransit = delaiTransit;
		this.client = client;
		this.transporteur = transporteur;
		this.portByIdport = portByIdport;
		this.portByPorIdport = portByPorIdport;
		this.moyennetransport = moyennetransport;
		this.transit = transit;
		this.commercial = commercial;
		this.cotation = cotation;
		this.date = date;
		this.etat = etat;
		this.incoter = incoter;
		this.typetransport = typetransport;
	}


	public Integer getNumdossier() {
		return this.numdossier;
	}

	public void setNumdossier(Integer numdossier) {
		this.numdossier = numdossier;
	}

	public Client getClient() {
		return this.client;
	}

	public void setClient(Client client) {
		this.client = client;
	}

	public Transporteur getTransporteur() {
		return this.transporteur;
	}

	public void setTransporteur(Transporteur transporteur) {
		this.transporteur = transporteur;
	}

	public Port getPortByIdport() {
		return this.portByIdport;
	}

	public void setPortByIdport(Port portByIdport) {
		this.portByIdport = portByIdport;
	}

	public Port getPortByPorIdport() {
		return this.portByPorIdport;
	}

	public void setPortByPorIdport(Port portByPorIdport) {
		this.portByPorIdport = portByPorIdport;
	}

	public Moyennetransport getMoyennetransport() {
		return this.moyennetransport;
	}

	public void setMoyennetransport(Moyennetransport moyennetransport) {
		this.moyennetransport = moyennetransport;
	}

	public Transit getTransit() {
		return this.transit;
	}

	public void setTransit(Transit transit) {
		this.transit = transit;
	}

	public Commercial getCommercial() {
		return this.commercial;
	}

	public void setCommercial(Commercial commercial) {
		this.commercial = commercial;
	}

	public Double getCotation() {
		return this.cotation;
	}

	public void setCotation(Double cotation) {
		this.cotation = cotation;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getEtat() {
		return this.etat;
	}

	public void setEtat(String etat) {
		this.etat = etat;
	}

	public String getIncoter() {
		return this.incoter;
	}

	public void setIncoter(String incoter) {
		this.incoter = incoter;
	}

	public String getTypetransport() {
		return this.typetransport;
	}

	public void setTypetransport(String typetransport) {
		this.typetransport = typetransport;
	}

	public Boolean getFintransport() {
		return this.fintransport;
	}

	public void setFintransport(Boolean fintransport) {
		this.fintransport = fintransport;
	}

	public Boolean getValidationclient() {
		return this.validationclient;
	}

	public void setValidationclient(Boolean validationclient) {
		this.validationclient = validationclient;
	}

	public int getDelaiTransit() {
		return delaiTransit;
	}

	public void setDelaiTransit(int delaiTransit) {
		this.delaiTransit = delaiTransit;
	}


	public Set<Comment> getCommentaires() {
		return commentaires;
	}


	public void setCommentaires(Set<Comment> commentaires) {
		this.commentaires = commentaires;
	}


	public Set<Etat> getEtats() {
		return etats;
	}


	public void setEtats(Set<Etat> etats) {
		this.etats = etats;
	}

}
