package dao;

// Generated 4 mars 2015 09:46:52 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Moyennetransport generated by hbm2java
 */
public class Moyennetransport implements java.io.Serializable {

	private Integer idmoyennetransport;
	private String moyennetransport;
	private Set<Dossier> dossiers = new HashSet<Dossier>(0);

	public Moyennetransport() {
	}

	public Moyennetransport(String moyennetransport) {
		this.moyennetransport = moyennetransport;
	}

	public Moyennetransport(String moyennetransport, Set<Dossier> dossiers) {
		this.moyennetransport = moyennetransport;
		this.dossiers = dossiers;
	}

	public Integer getIdmoyennetransport() {
		return this.idmoyennetransport;
	}

	public void setIdmoyennetransport(Integer idmoyennetransport) {
		this.idmoyennetransport = idmoyennetransport;
	}

	public String getMoyennetransport() {
		return this.moyennetransport;
	}

	public void setMoyennetransport(String moyennetransport) {
		this.moyennetransport = moyennetransport;
	}

	public Set<Dossier> getDossiers() {
		return this.dossiers;
	}

	public void setDossiers(Set<Dossier> dossiers) {
		this.dossiers = dossiers;
	}
	
	public String Afficher()
	{
		return moyennetransport;
	}

}
