package dao;

// Generated 4 mars 2015 09:46:52 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Port generated by hbm2java
 */
public class Port implements java.io.Serializable {

	private Integer idport;
	private Pays pays;
	private String nomport;
	private Set<Dossier> dossiersForPorIdport = new HashSet<Dossier>(0);
	private Set<Dossier> dossiersForIdport = new HashSet<Dossier>(0);

	public Port() {
	}

	public Port(Pays pays, String nomport) {
		this.pays = pays;
		this.nomport = nomport;
	}

	public Port(Pays pays, String nomport, Set<Dossier> dossiersForPorIdport,
			Set<Dossier> dossiersForIdport) {
		this.pays = pays;
		this.nomport = nomport;
		this.dossiersForPorIdport = dossiersForPorIdport;
		this.dossiersForIdport = dossiersForIdport;
	}

	public Integer getIdport() {
		return this.idport;
	}

	public void setIdport(Integer idport) {
		this.idport = idport;
	}

	public Pays getPays() {
		return this.pays;
	}

	public void setPays(Pays pays) {
		this.pays = pays;
	}

	public String getNomport() {
		return this.nomport;
	}

	public void setNomport(String nomport) {
		this.nomport = nomport;
	}

	public Set<Dossier> getDossiersForPorIdport() {
		return this.dossiersForPorIdport;
	}

	public void setDossiersForPorIdport(Set<Dossier> dossiersForPorIdport) {
		this.dossiersForPorIdport = dossiersForPorIdport;
	}

	public Set<Dossier> getDossiersForIdport() {
		return this.dossiersForIdport;
	}

	public void setDossiersForIdport(Set<Dossier> dossiersForIdport) {
		this.dossiersForIdport = dossiersForIdport;
	}
	public String Afficher()
	{
		return nomport+" "+pays.getPaysport();
	}
	
}
